services:
  cache_db:
    container_name: cache_db
    image: bitnami/redis:7.0-debian-12
    env_file:
      - ./cache_db/.env
    expose:
      - 6379
    restart: always
    volumes:
      - cache_db_data:/data/

  db:
    container_name: db
    image: mongo:8.0.0-rc13
    env_file:
      - ./db/.env
    expose:
      - 27017
    restart: always
    volumes:
      - db_data:/data/db/

  web_app:
    container_name: web_app
    build:
      context: ./web_app/
      dockerfile: dev.dockerfile
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    env_file:
      - ./web_app/.env
    expose:
      - 4000
    restart: always
    volumes:
      - ./web_app/app/:/app/app/:Z
    depends_on:
      - cache_db
      - db

  http:
    container_name: http
    build: ./http/
    ports:
      - 80:80
    restart: always
    depends_on:
      - app

volumes:
  db_data:
  cache_db_data:
